# Generated by Django 5.2.5 on 2025-09-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeedelivery',
            name='trigger_type',
            field=models.CharField(choices=[('api', 'API/Web Interface'), ('manual', 'Physical Button Press'), ('automatic', 'Automatic (Purge/System)')], default='api', max_length=20),
        ),
        migrations.AlterField(
            model_name='coffeedelivery',
            name='coffee_type',
            field=models.CharField(choices=[('single_short', 'Single Short'), ('single_medium', 'Single Medium'), ('single_long', 'Single Long'), ('double_short', 'Double Short'), ('double_medium', 'Double Medium'), ('double_long', 'Double Long'), ('purge', 'Purge Cycle')], max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='log_type',
            field=models.CharField(choices=[('purge', 'Purge'), ('cleaning', 'Cleaning'), ('sensor_fault', 'Sensor Fault'), ('connection_issue', 'Connection Issue'), ('manual_stop', 'Manual Stop'), ('health_check', 'Health Check'), ('manual_delivery', 'Manual Delivery')], max_length=20),
        ),
    ]
